---
title: "Ching's Week-13 diary on Webpage"
author: "Tang Ching Xian"
date: "2023-11-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


(1) Theme of the Data Story: 
The central theme of this data story revolves around the alarming global and local issue of food waste, emphasizing its severity both globally and specifically in Singapore. It delves into the environmental, economic, and social implications of wasting food, underscoring the critical importance of addressing this issue for the sake of a more sustainable and energy-efficient future.

(2) Importance of Addressing the Question: 
Addressing the question of food waste is crucial due to its multifaceted impact. Not only does it result in the squandering of valuable resources, but it also has significant environmental consequences, contributes to economic losses, and plays a role in global warming (UNEP, 2021; FAO, 2011; Zheng, 2019). By comprehending the scale of food waste and its various dimensions, society can work towards adopting more sustainable practices and create awareness about the necessity for responsible consumption.

(3) Relevance of Curated Data Sources: 
The curated data sources provide a comprehensive global perspective, utilizing statistics from reputable organizations like the United Nations’ Food and Agricultural Organisation (FAO, n.d.) and insights into greenhouse gas emissions (Crippa, 2021). The specific focus on Singapore's food industry and waste management practices adds a crucial localized perspective (NEA, n.d.). Additionally, the inclusion of data on recycling rates and innovative technologies, such as the anaerobic digester system, enriches the narrative by offering potential solutions to the complex issue of food waste (NEA, n.d.; Our World in Data, n.d.).

(4) Insights from the Data and Visualization: 
The data uncovers alarming statistics about global food waste, its economic cost, and its substantial contribution to greenhouse gas emissions (FAO, 2011; Crippa, 2021). Visualizations, including graphs illustrating the increase in greenhouse gas emissions from food production globally and the growth in the number of food factories in Singapore, emphasize the gravity of the situation. Interactive charts further highlight areas for improvement, such as recycling rates, with a specific focus on food and plastics waste (NEA, n.d.). The anaerobic digester system is presented as an innovative and sustainable solution, providing insights into its energy and fertilizer production (NUS, n.d.).

(5) Implementation of the Project and New Concepts Learned:
The project was executed through meticulous data gathering from reputable sources, exemplified by Our World in Data (2022), and presented in a visually engaging manner to extract profound insights. The integration of interactive features within the charts not only adds a layer of exploration for users but also significantly enhances their engagement with the data. The introduction of the anaerobic digester system represents a groundbreaking solution to the persistent issue of food waste, illustrating the pivotal role technology can play in transforming waste into valuable resources (NEA, n.d.). Moreover, the inclusion of a scatter graph with an r^2 regression coefficient sheds illuminating light on the correlation between a nation's food waste and its population size, underscoring the substantial influence of demographic factors on this pertinent issue (Our World in Data, 2022).

    Furthermore, the process of rendering the graph into an interactive format was both thrilling and challenging, requiring a profound understanding of Shiny and Tidyverse acquired during structured tutorials. This foundational knowledge set the stage for the evolution of a dynamic webpage. As the project unfolded, the exploration extended beyond structured tutorials, encompassing a diverse array of libraries. This expansion was not confined to traditional learning platforms but ventured into the vast expanse of YouTube, complemented by the invaluable guidance obtained from Google.

    The toolkit at my disposal was comprehensive, featuring libraries such as Shiny, Tidyverse, Highcharter, and more. Each library contributed a unique set of functionalities, enriching the landscape of my data visualization project. Particularly noteworthy were libraries like Flexdashboard and Plotly, providing subtle hints at the diverse visualizations I aspired to incorporate.

    Moving beyond the foundational knowledge acquired from tutorials, the real learning journey commenced as I delved into YouTube tutorials and sought assistance from Google. This self-directed learning not only exposed me to new libraries but also familiarized me with diverse syntax structures, broadening my comprehension of web development with Shiny.

    Undoubtedly, the journey was not without its challenges. Rendering issues and syntax errors became familiar companions. However, each challenge served as an invaluable opportunity to learn and refine my skills. Whether scouring online forums or delving into documentation, each problem-solving session added layers of expertise to my repertoire.

    Research emerged as a cornerstone of this journey, empowering me to navigate through online resources, from YouTube tutorials to forums, and confront challenges head-on. Solving problems not covered in tutorials enhanced my problem-solving skills and instilled a profound confidence in handling intricate issues.

    The arsenal of libraries showcased a diverse set of tools—HTMLtools for web elements, Viridis for color scales, Quarto for dynamic document generation, among others. Each library played a distinct role in elevating both the aesthetics and functionality of my webpage.

    The journey, albeit imperfect, stands as a testament to my unwavering dedication and evolving skills. Satisfaction was not derived from achieving perfection but rather from the iterative learning process itself.

    In conclusion, my exploration of Shiny and Tidyverse for web development unfolded as a tapestry woven with challenges and triumphs. Beyond the structured tutorials, the comprehensive exploration of diverse libraries and the resilience to overcome rendering issues and syntax errors defined this learning experience. The dynamic webpage crafted is not merely a visualization project but a reflection of my journey—a celebration of learning, problem-solving, and the satisfaction derived from striving for excellence amidst challenges.
    

Hopefully, my data story weaves together global and local perspectives, emphasizing the need for collective efforts to address food waste and promote sustainable practices. It encourages individuals to take responsibility and contribute to reducing food waste through recycling and mindful consumption, ultimately striving for a more sustainable and energy-efficient future.



----

Reference list:

Food and Agriculture Organization. (n.d.). The State of Food and Agriculture - 2019. https://www.fao.org/state-of-food-agriculture/2019/en/

Food and Agriculture Organization of the United Nations (FAO). (2011). Global food losses and food waste – Extent, causes and prevention. Rome. https://www.fao.org/3/mb060e/mb060e00.htm


National Environment Agency (NEA). (n.d.). Waste Statistics and Overall Recycling .https://www.nea.gov.sg/our-services/waste-management/waste-statistics-and-overall-recycling

Towards Zero Waste. (n.d.). Food Waste. https://www.towardszerowaste.gov.sg/foodwaste/

United Nation Environment Programme (UNEP). (2021). UNEP Food Waste Index Report 2021.https://www.unep.org/resources/report/unep-food-waste-index-report-2021

United Nation Environment Programme (UNEP). (2022, September 26). Why the global fight to tackle food waste has only just begun. https://www.unep.org/news-and-stories/story/why-global-fight-tackle-food-waste-has-only-just-begun

Zheng, Z. (2019, May 16). Food waste worsens climate change more than plastics: Zero waste Scotland report. https://mothership.sg/2019/05/food-waste-worsens-climate-change-more- than-plastics-zero-waste-scotland-report/


Data Sources:

Arvidsson, J. (n.d.). Food Waste [Data set]. Kaggle. https://www.kaggle.com/datasets/joebeachcapital/food-waste

National Environment Agency (NEA). (n.d.). Waste Statistics and Recycling Rate from 2003 to 2016 [Data set]. https://www.nea.gov.sg/docs/default-source/our-services/waste-management/wastestats-2003-20164197a3fd04d34770bafba09393d0fdf0.pdf

National Environment Agency (NEA). (n.d.). Waste Statistics and Recycling Rate from 2017 to 2021 [Data set]. https://www.nea.gov.sg/docs/default-source/default-document-library/waste-and-recycling-statistics-2017-to-2021.pdf

National Environment Agency (NEA). (n.d.). Waste Statistics and Recycling Rate for 2022 [Data set]. https://www.nea.gov.sg/our-services/waste-management/waste-statistics-and-overall-recycling


Our World in Data. (n.d). Waste Management. 
https://ourworldindata.org/waste-management

National University of Singapore. (n.d). Food Waste to Resources. Retrieved from https://nus.edu.sg/neri/research-features/food-waste-to-resources/
